print("Please enter the following information so I can sell it for profit!")
print()
name = input("First Name: ")
lname = input("Last Name: ")
grade = int(input("Grade(9-12): "))
sid = input("Student ID: ")
login = input("Login: ")
avg = float(input("Average: "))
print()

print("Your Information:")
print(f"    Login: {login}")
print(f"    ID: {sid}")
print(f"    Name: {lname.upper()}, {name.upper()}")
print(f"    Average: {round(avg,2)}")
print(f"    Grade: {grade}")