no1 = float(input("What is your first number?"))
no2 = float(input("What is your second number?"))
no3 = float(input("What is your third number?"))
print()
print(f"{no1} + {no2} + {no3} / 2 is ... {(no1+no2+no3)/2}")