input("Give me a word!")
print()
input("Give me a second word!")
print()
input(str("Give me your favourite number!"))
print()
input(str("Now your second favourite number?"))
print()
print("Whew! Wasn't that fun?")
